#log file, default is "stdout"
#log: stdout

#log level, default is "info"
#log_level: info

#http proxy for requesting "https://nmac.to", default is ""
#proxy:
#proxy: http://127.0.0.1:8118

#user agent for requesting "https://nmac.to", default is "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"
#user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36

#use image cache, default is true
#use_image_cache: true

#max cache db size, default is 104857600(100MB)
#max_cache_db_size: 104857600

#cache database dir, default is "./cache/db"
#cache_db_dir: ./cache/db

#cache image dir, default is "./cache/image"
#cache_image_dir: ./cache/image

#listen address, default is "0.0.0.0"
#listen_address: 0.0.0.0

#http port, default is 80
#http_port: 80

#enable https support, default is false
#https_support: false

#redirect to https, default is true
#redirect_to_https: true

#redirect to https code, default is 302
#redirect_to_https_code: 302

#https port, default is 443
#https_port: 443

#cert file, default is "./cert.cert"
#cert_file: ./cert.cert

#key file, default is "./cert.key"
#key_file: ./cert.key
